### ISSUE TITLE
pouchdb v5.4.0 breaks pouchdb-dump-cli v2.0.3

### ISSUE THREAD

**Issue by Pascalmh** [nolanlawson/pouchdb-dump-cli#14]
Using pouchdb@5.3.0 works fine, here is the error I get with v5.4.0:

```
unexpected error
{ [TypeError: this._get is not a function]
  result: 
   { ok: false,
     start_time: Tue Jun 07 2016 13:53:31 GMT+0200 (CEST),
     docs_read: 0,
     docs_written: 0,
     doc_write_failures: 0,
     errors: [ [Circular] ],
     status: 'aborting',
     end_time: Tue Jun 07 2016 13:53:31 GMT+0200 (CEST),
     last_seq: 0 } }
TypeError: this._get is not a function
    at PouchDB.<anonymous> (/node_modules/pouchdb/lib/index.js:2282:15)
    at PouchDB.<anonymous> (/node_modules/pouchdb/lib/index.js:207:21)
    at PouchDB.<anonymous> (/node_modules/argsarray/index.js:14:18)
    at /node_modules/pouchdb/lib/index.js:144:21
    at PouchDB.<anonymous> (/node_modules/pouchdb/lib/index.js:131:19)
    at PouchDB.get (/node_modules/argsarray/index.js:14:18)
    at getDocAttachmentsFromTargetOrSource (/node_modules/pouchdb/lib/index.js:7333:17)
    at /node_modules/pouchdb/lib/index.js:7408:18
    at Array.map (native)
    at /node_modules/pouchdb/lib/index.js:7395:50
```

**Comment by nolanlawson** [comment]
Hm yeah, looks like I'm using a private API that's not in there anymore. Will investigate.

**Comment by nolanlawson** [comment]
Gonna pin to 5.4.2 for the time being.

**Comment by nolanlawson** [comment]
pinned in 2.0.4
