### ISSUE TITLE
Unable to dump Cloudant DB in multiple files

### ISSUE THREAD

**Issue by sagarkm** [nolanlawson/pouchdb-dump-cli#17]
I tried "npm install -g pouchdb-dump-cli" and that installs pouchdb-dump but:

pouchdb-dump http://abcd.cloudant.com/master -u abcd -p XXXXX -o MasterDump.txt -s 10000
I am sure the password is RIGHT!
RETURNS: 
{"error":"unauthorized","reason":"Name or password is incorrect"}
unexpected error
{ [unauthorized: Name or password is incorrect.]
  status: 401,
  name: 'unauthorized',
  message: 'Name or password is incorrect.',
  error: true,
  reason: 'Name or password is incorrect' }

Alternately, I tried:
pouchdb-dump http://abcd:XXXXX@abcd.cloudant.com/master -o MasterDump.txt 

RETURNS:
unexpected error
{ [Error: getaddrinfo ENOTFOUND rts rts:80] status: 400 }
Error: getaddrinfo ENOTFOUND rts rts:80
    at onError (/usr/local/lib/node_modules/pouchdb-dump-cli/node_modules/pouchdb/lib/index.js:2599:18)
    at Request._callback (/usr/local/lib/node_modules/pouchdb-dump-cli/node_modules/pouchdb/lib/index.js:2640:14)
    at self.callback (/usr/local/lib/node_modules/pouchdb-dump-cli/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/pouchdb-dump-cli/node_modules/pouchdb/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)

It creates empty MasterDump.txt file.
Please help.

**Comment by sagarkm** [comment]
A note on above: My password had special characters that the terminal was unable to handle. Once I changed that password to plain text the below worked:
pouchdb-dump http://abcd.cloudant.com/master -u abcd -p XXXXX -o MasterDump.txt -s 5000

But gave difference errors on 2 attempts:
{ [Error: read ECONNRESET]
  status: 400,
  result: 
   { ok: false,
     start_time: Tue Sep 27 2016 15:13:27 GMT+0530 (IST),
     docs_read: 1500,
     docs_written: 1500,
     doc_write_failures: 0,
     errors: [ [Circular] ],
     last_seq: '106495-g1AAAAGjeJzLYWBgYMlgTmGQTUlKzi9KdUhJstQrzsnMS9dLzskvTUnMK9HLSy3JASpjSmRIsv___39WBnMSA0OGcC5QjN0wxSjVzNickH6QDXJwFYYGuKxIcgCSSfUIWxTAtpiYWCSlmCcRNINIj-SxAEmGBiAFtGg_xKb0R2CbEg0M04zSqOYfiE0HIDZB_ZT-CmyTpUmSaVpyIkFzsgAf4oYT',
     status: 'aborting',
     end_time: Tue Sep 27 2016 15:16:36 GMT+0530 (IST) } }
Error: read ECONNRESET
    at onError (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/lib/index.js:2599:18)
    at Request._callback (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/lib/index.js:2640:14)
    at self.callback (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)

And:
{ [Error: read ETIMEDOUT]
  status: 400,
  result: 
   { ok: false,
     start_time: Tue Sep 27 2016 16:23:10 GMT+0530 (IST),
     docs_read: 9000,
     docs_written: 9000,
     doc_write_failures: 0,
     errors: [ [Circular] ],
     last_seq: '113995-g1AAAAGjeJzLYWBgYMlgTmGQTUlKzi9KdUhJstQrzsnMS9dLzskvTUnMK9HLSy3JASpjSmRIsv___39WBnMSA0N-ai5QjN0wxSjVzNickH6QDXJwFYYGuKxIcgCSSfUIWwrAtpiYWCSlmCcRNINIj-SxAEmGBiAFtGg_1CZLsE2JBoZpRmlU8w_EpgMQm2B-sgXbZGmSZJqWnEjQnCwAdwKFfQ',
     status: 'aborting',
     end_time: Tue Sep 27 2016 16:29:10 GMT+0530 (IST) } }
Error: read ETIMEDOUT
    at onError (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/lib/index.js:2599:18)
    at Request._callback (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/lib/index.js:2640:14)
    at self.callback (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/node_modules/request/request.js:200:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/sagarmody/Work/temp/pouchdb-dump-cli/node_modules/pouchdb/node_modules/request/request.js:831:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)

Hope this helps.
