### ISSUE TITLE
Error: toString failed

### ISSUE THREAD

**Issue by sebseb30** [nolanlawson/pouchdb-dump-cli#18]
Hi,

I try to dump a big CouchDB base with attachments and I have some problem with this message 
It seems depend about the split size I take ...
And when I try to import with pouchdb-load it failed ...

If anywone can help :)

Thanks

```
Message :

Dumping 5604 docs, [                                        ] 0% 22656.8mbuffer.
js:379
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:379:11)
    at BufferList.toString (C:\Users\SEBROU.DOMEMI02\AppData\Roaming\npm\node_mo
dules\pouchdb-dump-cli\node_modules\request\node_modules\bl\bl.js:178:33)
    at Request.<anonymous> (C:\Users\SEBROU.DOMEMI02\AppData\Roaming\npm\node_mo
dules\pouchdb-dump-cli\node_modules\request\request.js:1042:32)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\SEBROU.DOMEMI02\AppData\Roaming\npm
\node_modules\pouchdb-dump-cli\node_modules\request\request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
```

**Comment by nolanlawson** [comment]
Hi, do you have a test case to reproduce? Otherwise it's hard to tell what needs to be fixed...
